id: A991B1AD9
title: f8F50
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:15:39.132640
  last_modified_at: 2022-05-27 17:15:39.132647
